### ISSUE TITLE
aborted CI

### ISSUE THREAD

**Issue by tboenig** [ulb-sachsen-anhalt/ulb-groundtruth-eval-odem-ger#6]
Dear Uwe,

The problem of the broken CI was not on your side.
The creation of the bagits was only limited to the following fileGrps:
`-q OCR-D-IMG -q GT-PAGE -q OCR-D-GT-SEG-PAGE -q OCR-D-GT-SEG-BLOCK -q OCR-D-GT-SEG-LINE `

I have added the fileGrp `OCR-D-GT-FULLTEXT` to the list. 
Show: 
https://github.com/OCR-D/gt-repo-scripts/blob/main/scripts/data_structure.sh

The workflow should now run through. 
I wish you good luck.

**Comment by M3ssman** [comment]
Thanks a lot it worked!
